package com.nexocriminal.domain.alerta;

public enum TipoAlerta {
    NODO_LOGISTICO,
    VEHICULO_APOYO,
    INTERMEDIARIO,
    POI_DESAPARICION,
    MODUS_OPERANDI,
    CLUSTER_DESAPARICIONES,
    DESAPARICION_NODO_SOSPECHOSO
}
